"""
Code Generation Agent — exports the entire pipeline to a Jupyter notebook.
"""

import nbformat as nbf
from typing import Dict, Any, Callable, Awaitable
import os

from ..llm.base import LLMProvider

class CodeGenAgent:
    """Agent that writes a reproducible Jupyter Notebook (.ipynb) of the pipeline."""

    def __init__(self, llm: LLMProvider):
        self.llm = llm

    async def run(
        self,
        dataset_path: str,
        target_column: str,
        problem_type: str,
        best_params: Dict[str, Any],
        model_type: str,
        eval_result: Dict[str, Any],
        log: Callable[[str], Awaitable[None]],
        test_size: float = 0.20
    ) -> str:
        """Generate and save the Jupyter Notebook."""
        await log(f"\n[bold magenta]● Code Generation Agent[/bold magenta] Exporting Jupyter Notebook...")
        
        nb = nbf.v4.new_notebook()

        cells = []

        # 1. Header
        cells.append(nbf.v4.new_markdown_cell(
            "# BeyondML Pipeline Export\n"
            "This notebook was automatically generated by BeyondML's Code Generation Agent.\n"
            "It reproduces the data loading, pre-processing, model training, and evaluation steps."
        ))

        # 2. Imports
        imports = (
            "import pandas as pd\n"
            "import numpy as np\n"
            "from sklearn.model_selection import train_test_split\n"
            "from sklearn.pipeline import Pipeline\n"
            "from sklearn.compose import ColumnTransformer\n"
            "from sklearn.impute import SimpleImputer\n"
            "from sklearn.preprocessing import StandardScaler, OneHotEncoder\n"
            "from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, RandomForestRegressor\n"
            "from sklearn.linear_model import LogisticRegression, LinearRegression\n"
            "from sklearn.svm import SVC, SVR\n"
            "import shap\n"
            "import joblib"
        )
        cells.append(nbf.v4.new_code_cell(imports))

        # 3. Data Loading
        cells.append(nbf.v4.new_markdown_cell("## 1. Load Data"))
        code_load = (
            f"dataset_path = '{dataset_path}'\n"
            f"target_col = '{target_column}'\n\n"
            f"df = pd.read_csv(dataset_path)\n"
            f"display(df.head())"
        )
        cells.append(nbf.v4.new_code_cell(code_load))

        # 4. Preprocessing
        cells.append(nbf.v4.new_markdown_cell("## 2. Preprocessing & Split"))
        code_prep = (
            f"X = df.drop(columns=[target_col])\n"
            f"y = df[target_col]\n\n"
            f"num_cols = [c for c in X.columns if pd.api.types.is_numeric_dtype(X[c])]\n"
            f"cat_cols = [c for c in X.columns if not pd.api.types.is_numeric_dtype(X[c])]\n\n"
            f"num_transformer = Pipeline([('imputer', SimpleImputer(strategy='median')), ('scaler', StandardScaler())])\n"
            f"cat_transformer = Pipeline([('imputer', SimpleImputer(strategy='most_frequent')), ('onehot', OneHotEncoder(handle_unknown='ignore'))])\n\n"
            f"preprocessor = ColumnTransformer(\n"
            f"    transformers=[('num', num_transformer, num_cols), ('cat', cat_transformer, cat_cols)],\n"
            f"    remainder='drop'\n"
            f")\n\n"
        )
        if problem_type == "classification":
            code_prep += f"X_train, X_test, y_train, y_test = train_test_split(X, y, test_size={test_size}, random_state=42, stratify=y)\n"
        else:
            code_prep += f"X_train, X_test, y_train, y_test = train_test_split(X, y, test_size={test_size}, random_state=42)\n"
            
        cells.append(nbf.v4.new_code_cell(code_prep))

        # 5. Model
        cells.append(nbf.v4.new_markdown_cell("## 3. Train Model"))
        model_kwargs = ", ".join([f"{k}={repr(v)}" for k, v in best_params.items()])
        code_model = (
            f"model = {model_type}({model_kwargs})\n"
            f"pipeline = Pipeline([('preprocessor', preprocessor), ('model', model)])\n\n"
            f"pipeline.fit(X_train, y_train)\n"
            f"print('Test Score:', pipeline.score(X_test, y_test))"
        )
        cells.append(nbf.v4.new_code_cell(code_model))

        # 6. Saving
        cells.append(nbf.v4.new_markdown_cell("## 4. Explainability (SHAP)"))
        code_shap = (
            "try:\n"
            "    X_sample = pipeline.named_steps['preprocessor'].transform(X_test[:100])\n"
            "    feature_names = pipeline.named_steps['preprocessor'].get_feature_names_out()\n"
            "    feature_names = [f.split('__')[-1] for f in feature_names]\n\n"
            "    explainer = shap.Explainer(pipeline.named_steps['model'])\n"
            "    shap_values = explainer(X_sample)\n"
            "    import matplotlib.pyplot as plt\n"
            "    shap.summary_plot(shap_values, X_sample, feature_names=feature_names)\n"
            "except Exception as e:\n"
            "    print('Could not generate SHAP plots:', e)"
        )
        cells.append(nbf.v4.new_code_cell(code_shap))

        nb['cells'] = cells
        
        os.makedirs("workspace", exist_ok=True)
        out_path = os.path.join("workspace", "pipeline_export.ipynb")
        
        with open(out_path, 'w', encoding='utf-8') as f:
            nbf.write(nb, f)

        await log(f"  [green]✓ Notebook saved to {out_path}[/green]")
        return out_path
